/* tslint:disable */
/* eslint-disable */
/**
 * rag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocListDocChunks200ResponseChunkListInner } from './doc-list-doc-chunks200-response-chunk-list-inner';

export interface DocListDocChunks200Response {
    'chunkList'?: Array<DocListDocChunks200ResponseChunkListInner>;
    'total'?: number;
}

