/* tslint:disable */
/* eslint-disable */
/**
 * rag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocListDoc200ResponseDocumentListInner } from './doc-list-doc200-response-document-list-inner';

export interface DocListDoc200Response {
    'documentList'?: Array<DocListDoc200ResponseDocumentListInner>;
    'total'?: number;
}

