/* tslint:disable */
/* eslint-disable */
/**
 * llm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
<<<<<<< HEAD
 * The version of the OpenAPI document: v1
=======
 * The version of the OpenAPI document: 0.0.1
>>>>>>> 99277053c4a27964f631dcd7ef16adb410b9c2b2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChatsessionListChatSession200ResponseSessionsInner } from './chatsession-list-chat-session200-response-sessions-inner';

export interface ChatsessionGetChatSession200Response {
    'session'?: ChatsessionListChatSession200ResponseSessionsInner;
}

