/* tslint:disable */
/* eslint-disable */
/**
 * llm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChatmessageListChatMessageBySessionRequestPageQuery } from './chatmessage-list-chat-message-by-session-request-page-query';
// May contain unused imports in some cases
// @ts-ignore
import type { ChatsessionListChatSessionRequestFilter } from './chatsession-list-chat-session-request-filter';

export interface ChatsessionListChatSessionRequest {
    'filter'?: ChatsessionListChatSessionRequestFilter;
    'pageQuery': ChatmessageListChatMessageBySessionRequestPageQuery;
}

