/* tslint:disable */
/* eslint-disable */
/**
 * llm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConfigListMyConfigRequestPageQuery } from './config-list-my-config-request-page-query';
// May contain unused imports in some cases
// @ts-ignore
import type { ConfigListMyConfigRequestQueryFilter } from './config-list-my-config-request-query-filter';

export interface ConfigListMyConfigRequest {
    'pageQuery': ConfigListMyConfigRequestPageQuery;
    'queryFilter': ConfigListMyConfigRequestQueryFilter;
}

