/* tslint:disable */
/* eslint-disable */
/**
 * llm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ConfigCreateConfig200Response } from '../model';
// @ts-ignore
import type { ConfigCreateConfigBody } from '../model';
// @ts-ignore
import type { ConfigGetConfig200Response } from '../model';
// @ts-ignore
import type { ConfigListMyConfig200Response } from '../model';
// @ts-ignore
import type { ConfigListMyConfigRequest } from '../model';
/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 创建配置
         * @param {ConfigCreateConfigBody} configCreateConfigBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configCreateConfig: async (configCreateConfigBody: ConfigCreateConfigBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'configCreateConfigBody' is not null or undefined
            assertParamExists('configCreateConfig', 'configCreateConfigBody', configCreateConfigBody)
            const localVarPath = `/llm/v1/config/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(configCreateConfigBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除配置
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configDeleteConfig: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('configDeleteConfig', 'id', id)
            const localVarPath = `/llm/v1/config/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取配置详情
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configGetConfig: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('configGetConfig', 'id', id)
            const localVarPath = `/llm/v1/config/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 分页查询我的配置
         * @param {ConfigListMyConfigRequest} configListMyConfigRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configListMyConfig: async (configListMyConfigRequest: ConfigListMyConfigRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'configListMyConfigRequest' is not null or undefined
            assertParamExists('configListMyConfig', 'configListMyConfigRequest', configListMyConfigRequest)
            const localVarPath = `/llm/v1/config/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(configListMyConfigRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新配置
         * @param {number} id 
         * @param {ConfigCreateConfigBody} configCreateConfigBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configUpdateConfig: async (id: number, configCreateConfigBody: ConfigCreateConfigBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('configUpdateConfig', 'id', id)
            // verify required parameter 'configCreateConfigBody' is not null or undefined
            assertParamExists('configUpdateConfig', 'configCreateConfigBody', configCreateConfigBody)
            const localVarPath = `/llm/v1/config/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(configCreateConfigBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 创建配置
         * @param {ConfigCreateConfigBody} configCreateConfigBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async configCreateConfig(configCreateConfigBody: ConfigCreateConfigBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConfigCreateConfig200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.configCreateConfig(configCreateConfigBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.configCreateConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 删除配置
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async configDeleteConfig(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.configDeleteConfig(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.configDeleteConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取配置详情
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async configGetConfig(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConfigGetConfig200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.configGetConfig(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.configGetConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 分页查询我的配置
         * @param {ConfigListMyConfigRequest} configListMyConfigRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async configListMyConfig(configListMyConfigRequest: ConfigListMyConfigRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConfigListMyConfig200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.configListMyConfig(configListMyConfigRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.configListMyConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 更新配置
         * @param {number} id 
         * @param {ConfigCreateConfigBody} configCreateConfigBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async configUpdateConfig(id: number, configCreateConfigBody: ConfigCreateConfigBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.configUpdateConfig(id, configCreateConfigBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.configUpdateConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary 创建配置
         * @param {ConfigCreateConfigBody} configCreateConfigBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configCreateConfig(configCreateConfigBody: ConfigCreateConfigBody, options?: RawAxiosRequestConfig): AxiosPromise<ConfigCreateConfig200Response> {
            return localVarFp.configCreateConfig(configCreateConfigBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除配置
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configDeleteConfig(id: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.configDeleteConfig(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取配置详情
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configGetConfig(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ConfigGetConfig200Response> {
            return localVarFp.configGetConfig(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 分页查询我的配置
         * @param {ConfigListMyConfigRequest} configListMyConfigRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configListMyConfig(configListMyConfigRequest: ConfigListMyConfigRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConfigListMyConfig200Response> {
            return localVarFp.configListMyConfig(configListMyConfigRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新配置
         * @param {number} id 
         * @param {ConfigCreateConfigBody} configCreateConfigBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configUpdateConfig(id: number, configCreateConfigBody: ConfigCreateConfigBody, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.configUpdateConfig(id, configCreateConfigBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary 创建配置
     * @param {ConfigCreateConfigBody} configCreateConfigBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public configCreateConfig(configCreateConfigBody: ConfigCreateConfigBody, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).configCreateConfig(configCreateConfigBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 删除配置
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public configDeleteConfig(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).configDeleteConfig(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取配置详情
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public configGetConfig(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).configGetConfig(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 分页查询我的配置
     * @param {ConfigListMyConfigRequest} configListMyConfigRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public configListMyConfig(configListMyConfigRequest: ConfigListMyConfigRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).configListMyConfig(configListMyConfigRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新配置
     * @param {number} id 
     * @param {ConfigCreateConfigBody} configCreateConfigBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public configUpdateConfig(id: number, configCreateConfigBody: ConfigCreateConfigBody, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).configUpdateConfig(id, configCreateConfigBody, options).then((request) => request(this.axios, this.basePath));
    }
}

