/* tslint:disable */
/* eslint-disable */
/**
 * voicechat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AsrCreateAsrConfig200Response } from '../model';
// @ts-ignore
import type { AsrCreateAsrConfigBody } from '../model';
// @ts-ignore
import type { AsrGetAsrConfig200Response } from '../model';
// @ts-ignore
import type { AsrListAsrConfig200Response } from '../model';
// @ts-ignore
import type { AsrListAsrConfigBody } from '../model';
// @ts-ignore
import type { ChatStartRequest } from '../model';
// @ts-ignore
import type { TtsCreateTtsConfigBody } from '../model';
// @ts-ignore
import type { TtsGetTtsConfig200Response } from '../model';
// @ts-ignore
import type { TtsListTtsConfig200Response } from '../model';
/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 创建ASR配置
         * @param {AsrCreateAsrConfigBody} asrCreateAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrCreateAsrConfig: async (asrCreateAsrConfigBody: AsrCreateAsrConfigBody, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'asrCreateAsrConfigBody' is not null or undefined
            assertParamExists('asrCreateAsrConfig', 'asrCreateAsrConfigBody', asrCreateAsrConfigBody)
            const localVarPath = `/voice/v1/asr/config`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(asrCreateAsrConfigBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除ASR配置
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrDeleteAsrConfig: async (id: number, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('asrDeleteAsrConfig', 'id', id)
            const localVarPath = `/voice/v1/asr/config/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取ASR配置详情
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrGetAsrConfig: async (id: number, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('asrGetAsrConfig', 'id', id)
            const localVarPath = `/voice/v1/asr/config/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 分页获取ASR配置列表
         * @param {AsrListAsrConfigBody} asrListAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrListAsrConfig: async (asrListAsrConfigBody: AsrListAsrConfigBody, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'asrListAsrConfigBody' is not null or undefined
            assertParamExists('asrListAsrConfig', 'asrListAsrConfigBody', asrListAsrConfigBody)
            const localVarPath = `/voice/v1/asr/configs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(asrListAsrConfigBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新ASR配置
         * @param {number} id 
         * @param {AsrCreateAsrConfigBody} asrCreateAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrUpdateAsrConfig: async (id: number, asrCreateAsrConfigBody: AsrCreateAsrConfigBody, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('asrUpdateAsrConfig', 'id', id)
            // verify required parameter 'asrCreateAsrConfigBody' is not null or undefined
            assertParamExists('asrUpdateAsrConfig', 'asrCreateAsrConfigBody', asrCreateAsrConfigBody)
            const localVarPath = `/voice/v1/asr/config/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(asrCreateAsrConfigBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 创建websocket连接,然后帮助建立webrtc连接
         * @param {ChatStartRequest} chatStartRequest 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatStart: async (chatStartRequest: ChatStartRequest, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatStartRequest' is not null or undefined
            assertParamExists('chatStart', 'chatStartRequest', chatStartRequest)
            const localVarPath = `/voice/v1/chat/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(chatStartRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 创建TTS配置
         * @param {TtsCreateTtsConfigBody} ttsCreateTtsConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ttsCreateTtsConfig: async (ttsCreateTtsConfigBody: TtsCreateTtsConfigBody, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ttsCreateTtsConfigBody' is not null or undefined
            assertParamExists('ttsCreateTtsConfig', 'ttsCreateTtsConfigBody', ttsCreateTtsConfigBody)
            const localVarPath = `/voice/v1/tts/config`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ttsCreateTtsConfigBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除TTS配置
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ttsDeleteTtsConfig: async (id: number, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('ttsDeleteTtsConfig', 'id', id)
            const localVarPath = `/voice/v1/tts/config/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取TTS配置详情
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ttsGetTtsConfig: async (id: number, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('ttsGetTtsConfig', 'id', id)
            const localVarPath = `/voice/v1/tts/config/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 分页获取TTS配置列表
         * @param {AsrListAsrConfigBody} asrListAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ttsListTtsConfig: async (asrListAsrConfigBody: AsrListAsrConfigBody, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'asrListAsrConfigBody' is not null or undefined
            assertParamExists('ttsListTtsConfig', 'asrListAsrConfigBody', asrListAsrConfigBody)
            const localVarPath = `/voice/v1/tts/configs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(asrListAsrConfigBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新TTS配置
         * @param {number} id 
         * @param {TtsCreateTtsConfigBody} ttsCreateTtsConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ttsUpdateTtsConfig: async (id: number, ttsCreateTtsConfigBody: TtsCreateTtsConfigBody, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('ttsUpdateTtsConfig', 'id', id)
            // verify required parameter 'ttsCreateTtsConfigBody' is not null or undefined
            assertParamExists('ttsUpdateTtsConfig', 'ttsCreateTtsConfigBody', ttsCreateTtsConfigBody)
            const localVarPath = `/voice/v1/tts/config/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ttsCreateTtsConfigBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 创建ASR配置
         * @param {AsrCreateAsrConfigBody} asrCreateAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async asrCreateAsrConfig(asrCreateAsrConfigBody: AsrCreateAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AsrCreateAsrConfig200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.asrCreateAsrConfig(asrCreateAsrConfigBody, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.asrCreateAsrConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 删除ASR配置
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async asrDeleteAsrConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.asrDeleteAsrConfig(id, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.asrDeleteAsrConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取ASR配置详情
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async asrGetAsrConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AsrGetAsrConfig200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.asrGetAsrConfig(id, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.asrGetAsrConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 分页获取ASR配置列表
         * @param {AsrListAsrConfigBody} asrListAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async asrListAsrConfig(asrListAsrConfigBody: AsrListAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AsrListAsrConfig200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.asrListAsrConfig(asrListAsrConfigBody, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.asrListAsrConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 更新ASR配置
         * @param {number} id 
         * @param {AsrCreateAsrConfigBody} asrCreateAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async asrUpdateAsrConfig(id: number, asrCreateAsrConfigBody: AsrCreateAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.asrUpdateAsrConfig(id, asrCreateAsrConfigBody, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.asrUpdateAsrConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 创建websocket连接,然后帮助建立webrtc连接
         * @param {ChatStartRequest} chatStartRequest 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatStart(chatStartRequest: ChatStartRequest, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatStart(chatStartRequest, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.chatStart']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 创建TTS配置
         * @param {TtsCreateTtsConfigBody} ttsCreateTtsConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ttsCreateTtsConfig(ttsCreateTtsConfigBody: TtsCreateTtsConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AsrCreateAsrConfig200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ttsCreateTtsConfig(ttsCreateTtsConfigBody, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.ttsCreateTtsConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 删除TTS配置
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ttsDeleteTtsConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ttsDeleteTtsConfig(id, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.ttsDeleteTtsConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取TTS配置详情
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ttsGetTtsConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TtsGetTtsConfig200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ttsGetTtsConfig(id, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.ttsGetTtsConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 分页获取TTS配置列表
         * @param {AsrListAsrConfigBody} asrListAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ttsListTtsConfig(asrListAsrConfigBody: AsrListAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TtsListTtsConfig200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ttsListTtsConfig(asrListAsrConfigBody, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.ttsListTtsConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 更新TTS配置
         * @param {number} id 
         * @param {TtsCreateTtsConfigBody} ttsCreateTtsConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ttsUpdateTtsConfig(id: number, ttsCreateTtsConfigBody: TtsCreateTtsConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ttsUpdateTtsConfig(id, ttsCreateTtsConfigBody, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.ttsUpdateTtsConfig']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary 创建ASR配置
         * @param {AsrCreateAsrConfigBody} asrCreateAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrCreateAsrConfig(asrCreateAsrConfigBody: AsrCreateAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<AsrCreateAsrConfig200Response> {
            return localVarFp.asrCreateAsrConfig(asrCreateAsrConfigBody, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除ASR配置
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrDeleteAsrConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.asrDeleteAsrConfig(id, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取ASR配置详情
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrGetAsrConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<AsrGetAsrConfig200Response> {
            return localVarFp.asrGetAsrConfig(id, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 分页获取ASR配置列表
         * @param {AsrListAsrConfigBody} asrListAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrListAsrConfig(asrListAsrConfigBody: AsrListAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<AsrListAsrConfig200Response> {
            return localVarFp.asrListAsrConfig(asrListAsrConfigBody, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新ASR配置
         * @param {number} id 
         * @param {AsrCreateAsrConfigBody} asrCreateAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asrUpdateAsrConfig(id: number, asrCreateAsrConfigBody: AsrCreateAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.asrUpdateAsrConfig(id, asrCreateAsrConfigBody, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 创建websocket连接,然后帮助建立webrtc连接
         * @param {ChatStartRequest} chatStartRequest 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatStart(chatStartRequest: ChatStartRequest, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.chatStart(chatStartRequest, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 创建TTS配置
         * @param {TtsCreateTtsConfigBody} ttsCreateTtsConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ttsCreateTtsConfig(ttsCreateTtsConfigBody: TtsCreateTtsConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<AsrCreateAsrConfig200Response> {
            return localVarFp.ttsCreateTtsConfig(ttsCreateTtsConfigBody, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除TTS配置
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ttsDeleteTtsConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.ttsDeleteTtsConfig(id, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取TTS配置详情
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ttsGetTtsConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<TtsGetTtsConfig200Response> {
            return localVarFp.ttsGetTtsConfig(id, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 分页获取TTS配置列表
         * @param {AsrListAsrConfigBody} asrListAsrConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ttsListTtsConfig(asrListAsrConfigBody: AsrListAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<TtsListTtsConfig200Response> {
            return localVarFp.ttsListTtsConfig(asrListAsrConfigBody, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新TTS配置
         * @param {number} id 
         * @param {TtsCreateTtsConfigBody} ttsCreateTtsConfigBody 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ttsUpdateTtsConfig(id: number, ttsCreateTtsConfigBody: TtsCreateTtsConfigBody, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.ttsUpdateTtsConfig(id, ttsCreateTtsConfigBody, xUserId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary 创建ASR配置
     * @param {AsrCreateAsrConfigBody} asrCreateAsrConfigBody 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public asrCreateAsrConfig(asrCreateAsrConfigBody: AsrCreateAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).asrCreateAsrConfig(asrCreateAsrConfigBody, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 删除ASR配置
     * @param {number} id 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public asrDeleteAsrConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).asrDeleteAsrConfig(id, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取ASR配置详情
     * @param {number} id 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public asrGetAsrConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).asrGetAsrConfig(id, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 分页获取ASR配置列表
     * @param {AsrListAsrConfigBody} asrListAsrConfigBody 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public asrListAsrConfig(asrListAsrConfigBody: AsrListAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).asrListAsrConfig(asrListAsrConfigBody, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新ASR配置
     * @param {number} id 
     * @param {AsrCreateAsrConfigBody} asrCreateAsrConfigBody 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public asrUpdateAsrConfig(id: number, asrCreateAsrConfigBody: AsrCreateAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).asrUpdateAsrConfig(id, asrCreateAsrConfigBody, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 创建websocket连接,然后帮助建立webrtc连接
     * @param {ChatStartRequest} chatStartRequest 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public chatStart(chatStartRequest: ChatStartRequest, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).chatStart(chatStartRequest, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 创建TTS配置
     * @param {TtsCreateTtsConfigBody} ttsCreateTtsConfigBody 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public ttsCreateTtsConfig(ttsCreateTtsConfigBody: TtsCreateTtsConfigBody, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).ttsCreateTtsConfig(ttsCreateTtsConfigBody, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 删除TTS配置
     * @param {number} id 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public ttsDeleteTtsConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).ttsDeleteTtsConfig(id, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取TTS配置详情
     * @param {number} id 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public ttsGetTtsConfig(id: number, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).ttsGetTtsConfig(id, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 分页获取TTS配置列表
     * @param {AsrListAsrConfigBody} asrListAsrConfigBody 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public ttsListTtsConfig(asrListAsrConfigBody: AsrListAsrConfigBody, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).ttsListTtsConfig(asrListAsrConfigBody, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新TTS配置
     * @param {number} id 
     * @param {TtsCreateTtsConfigBody} ttsCreateTtsConfigBody 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public ttsUpdateTtsConfig(id: number, ttsCreateTtsConfigBody: TtsCreateTtsConfigBody, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).ttsUpdateTtsConfig(id, ttsCreateTtsConfigBody, xUserId, options).then((request) => request(this.axios, this.basePath));
    }
}

