/* tslint:disable */
/* eslint-disable */
/**
 * voicechat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AsrListAsrConfig200ResponseConfigListInner } from './asr-list-asr-config200-response-config-list-inner';

export interface AsrListAsrConfig200Response {
    'configList'?: Array<AsrListAsrConfig200ResponseConfigListInner>;
    'total'?: number;
}

