/* tslint:disable */
/* eslint-disable */
/**
 * voicechat
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChatStartRequestAsrConfig } from './chat-start-request-asr-config';
// May contain unused imports in some cases
// @ts-ignore
import type { ChatStartRequestLlmConfig } from './chat-start-request-llm-config';
// May contain unused imports in some cases
// @ts-ignore
import type { ChatStartRequestTtsConfig } from './chat-start-request-tts-config';

export interface ChatStartRequest {
    'asrConfig': ChatStartRequestAsrConfig;
    'knowledgeInfo': string;
    'llmConfig': ChatStartRequestLlmConfig;
    'ttsConfig': ChatStartRequestTtsConfig;
}

