/* tslint:disable */
/* eslint-disable */
/**
 * rag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DocDeleteDoc200Response } from '../model';
// @ts-ignore
import type { DocListDoc200Response } from '../model';
// @ts-ignore
import type { DocListDocChunks200Response } from '../model';
// @ts-ignore
import type { DocListDocChunksRequest } from '../model';
// @ts-ignore
import type { DocListDocRequest } from '../model';
// @ts-ignore
import type { DocUploadAndEmbed200Response } from '../model';
/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 删除上传文件
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        docDeleteDoc: async (id: number, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('docDeleteDoc', 'id', id)
            const localVarPath = `/rag/v1/doc/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 分页查询上传文件
         * @param {DocListDocRequest} docListDocRequest 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        docListDoc: async (docListDocRequest: DocListDocRequest, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'docListDocRequest' is not null or undefined
            assertParamExists('docListDoc', 'docListDocRequest', docListDocRequest)
            const localVarPath = `/rag/v1/doc/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(docListDocRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 分页查询文件切片
         * @param {string} fileId 
         * @param {DocListDocChunksRequest} docListDocChunksRequest 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        docListDocChunks: async (fileId: string, docListDocChunksRequest: DocListDocChunksRequest, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('docListDocChunks', 'fileId', fileId)
            // verify required parameter 'docListDocChunksRequest' is not null or undefined
            assertParamExists('docListDocChunks', 'docListDocChunksRequest', docListDocChunksRequest)
            const localVarPath = `/rag/v1/doc/{fileId}/chunks`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(docListDocChunksRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 上传文件并向量化
         * @param {string} filename 
         * @param {File} file 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        docUploadAndEmbed: async (filename: string, file: File, xUserId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'filename' is not null or undefined
            assertParamExists('docUploadAndEmbed', 'filename', filename)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('docUploadAndEmbed', 'file', file)
            const localVarPath = `/rag/v1/doc/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (filename !== undefined) { 
                localVarFormParams.append('filename', filename as any);
            }
    
            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            if (xUserId != null) {
                localVarHeaderParameter['X-User-Id'] = typeof xUserId === 'string'
                    ? xUserId
                    : JSON.stringify(xUserId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 删除上传文件
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async docDeleteDoc(id: number, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocDeleteDoc200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.docDeleteDoc(id, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.docDeleteDoc']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 分页查询上传文件
         * @param {DocListDocRequest} docListDocRequest 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async docListDoc(docListDocRequest: DocListDocRequest, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocListDoc200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.docListDoc(docListDocRequest, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.docListDoc']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 分页查询文件切片
         * @param {string} fileId 
         * @param {DocListDocChunksRequest} docListDocChunksRequest 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async docListDocChunks(fileId: string, docListDocChunksRequest: DocListDocChunksRequest, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocListDocChunks200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.docListDocChunks(fileId, docListDocChunksRequest, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.docListDocChunks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 上传文件并向量化
         * @param {string} filename 
         * @param {File} file 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async docUploadAndEmbed(filename: string, file: File, xUserId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocUploadAndEmbed200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.docUploadAndEmbed(filename, file, xUserId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.docUploadAndEmbed']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary 删除上传文件
         * @param {number} id 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        docDeleteDoc(id: number, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<DocDeleteDoc200Response> {
            return localVarFp.docDeleteDoc(id, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 分页查询上传文件
         * @param {DocListDocRequest} docListDocRequest 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        docListDoc(docListDocRequest: DocListDocRequest, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<DocListDoc200Response> {
            return localVarFp.docListDoc(docListDocRequest, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 分页查询文件切片
         * @param {string} fileId 
         * @param {DocListDocChunksRequest} docListDocChunksRequest 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        docListDocChunks(fileId: string, docListDocChunksRequest: DocListDocChunksRequest, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<DocListDocChunks200Response> {
            return localVarFp.docListDocChunks(fileId, docListDocChunksRequest, xUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 上传文件并向量化
         * @param {string} filename 
         * @param {File} file 
         * @param {number} [xUserId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        docUploadAndEmbed(filename: string, file: File, xUserId?: number, options?: RawAxiosRequestConfig): AxiosPromise<DocUploadAndEmbed200Response> {
            return localVarFp.docUploadAndEmbed(filename, file, xUserId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary 删除上传文件
     * @param {number} id 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public docDeleteDoc(id: number, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).docDeleteDoc(id, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 分页查询上传文件
     * @param {DocListDocRequest} docListDocRequest 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public docListDoc(docListDocRequest: DocListDocRequest, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).docListDoc(docListDocRequest, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 分页查询文件切片
     * @param {string} fileId 
     * @param {DocListDocChunksRequest} docListDocChunksRequest 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public docListDocChunks(fileId: string, docListDocChunksRequest: DocListDocChunksRequest, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).docListDocChunks(fileId, docListDocChunksRequest, xUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 上传文件并向量化
     * @param {string} filename 
     * @param {File} file 
     * @param {number} [xUserId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public docUploadAndEmbed(filename: string, file: File, xUserId?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).docUploadAndEmbed(filename, file, xUserId, options).then((request) => request(this.axios, this.basePath));
    }
}

